services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - 3307:3306
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - 3306:3306
  myrest:
    build: .
    image: greicodex/myrest:latest
    ports:
      - 3000:3000
    environment:
#      - DATABASE_HOST=mysql
#      - DATABASE_USER=root
#      - DATABASE_PASSWORD=toor
#      - DATABASE_NAME=mysql
#  # Example using DATABASE_URL with SSL
      - DATABASE_URL=mysql://root:toor@mysql:3306/mysql?ssl=false
      - JWT_SECRET=wdlnds_secret_token
      - JWT_REQUIRED=true
    depends_on:
      - mysql
  

